### ISSUE TITLE
Example fusion mutation file

### ISSUE THREAD

**Issue by aleonti** [stjude/NeoepitopePred#1]
I'm trying to run the Neoepitope prediction pipeline on the St. Jude Cloud with my lab's own data, but the instructions are a little unclear in regards to the "mutation file" required as input for the pipeline. I'm interested in using this pipeline for gene fusions, but I couldn't find much information about what needs to be in the gene fusion mutation file. Do you have a template or example of a gene fusion mutation file? What columns/rows are necessary, and how might that differ from the SNV mutation file? I apologize if there's already something like that in one of these repos and I missed it. 

Thank you!

**Comment by kirbyjbirch** [comment]
[test.fusion.txt](https://github.com/stjude/NeoepitopePred/files/2063059/test.fusion.txt)

Hi Amanda,
 
We’re sorry to hear the documentation did not convey this clearly enough, and we will work to make the documentation more detailed for future reference.
 
The fusion part is based on the CICERO output. For an example file of the minimum required fields for running the prediction, please see test.fusion.txt I hope that this helps, and please let me know if you need any more information.
 
Kirby
